---
vars:
  region: "%{hiera('region')}"

  component: "%{hiera('component')}"
  deployment_identifier: "%{hiera('specific_deployment_identifier')}"
  task_name: "cert-manager"

  version_number: "%{hiera('cert_manager_version_number')}"

  secrets_bucket_name: "%{hiera('specific_storage_bucket_name')}"

  key_store_password: "%{hiera('key_store_password')}"

  common_state_bucket_name: "%{hiera('common_state_bucket_name')}"
  common_state_key: "%{hiera('common_state_key')}"

  network_state_bucket_name: "%{hiera('network_state_bucket_name')}"
  network_state_key: "%{hiera('network_state_key')}"

  cluster_state_bucket_name: "%{hiera('cluster_state_bucket_name')}"
  cluster_state_key: "%{hiera('cluster_state_key')}"

  image_repository_state_bucket_name: "%{hiera('cert_manager_image_repository_state_bucket_name')}"
  image_repository_state_key: "%{hiera('cert_manager_image_repository_state_key')}"

backend_config:
  bucket: "%{hiera('cert_manager_task_state_bucket_name')}"
  key: "%{hiera('cert_manager_task_state_key')}"
  region: "%{hiera('region')}"
  encrypt: "true"
